name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: 
      image: gcc:15.2.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        g++ --version

    - name: Install Meson
      run: |
        pip3 install --upgrade pip
        pip3 install meson

    - name: Cache Meson and Ninja
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/meson
          ~/.cache/ninja
        key: ${{ runner.os }}-meson-ninja-${{ hashFiles('**/meson.build') }}
        restore-keys: |
          ${{ runner.os }}-meson-ninja-

    - name: Setup build directory
      run: |
        meson setup build --reconfigure

    - name: Build project
      run: |
        meson compile -C build

    - name: Run tests
      run: |
        meson test -C build --verbose
