name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: gcc:15  # Alternative: Use GCC 15 container

    steps:
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          ninja-build \
          pkg-config \
          python3 \
          python3-pip

    - name: Install Meson
      run: |
        pip3 install --upgrade pip
        pip3 install meson

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup build directory
      run: |
        meson setup build --reconfigure

    - name: Build project
      run: |
        meson compile -C build

    - name: Run tests
      run: |
        meson test -C build --verbose
